from __future__ import annotations

from .frontier import FRONTIER_DOMINANCE_RATIO, explain_path_breakdown, prune_growth_frontier
from .pairs import SINCE_PATTERN, parse_finished_at_utc, parse_since, resolve_snapshot_pairs
from .queries import (
    ReportError,
    parse_report_limit,
    query_deleted_rows,
    query_diff_rows,
    query_explain_path_rows,
    query_indexed_storage_domain_totals,
    query_top_rows,
    resolve_group_for_path,
    resolve_top_level_subtree_group,
    resolve_top_snapshot_selection,
    summarize_diff_rows,
)
from .render import (
    decode_path,
    path_payload,
    render_deleted_open_payload,
    render_deleted_open_text,
    render_deleted_payload,
    render_deleted_text,
    render_df_index_payload,
    render_df_index_text,
    render_diff_payload,
    render_diff_text,
    render_docker_enrichment_payload,
    render_docker_enrichment_text,
    render_explain_path_payload,
    render_explain_path_text,
    render_report_payload,
    render_report_text,
    render_top_payload,
    render_top_text,
)

__all__ = [
    "FRONTIER_DOMINANCE_RATIO",
    "ReportError",
    "SINCE_PATTERN",
    "decode_path",
    "explain_path_breakdown",
    "parse_finished_at_utc",
    "parse_report_limit",
    "parse_since",
    "path_payload",
    "prune_growth_frontier",
    "query_deleted_rows",
    "query_diff_rows",
    "query_explain_path_rows",
    "query_indexed_storage_domain_totals",
    "query_top_rows",
    "render_deleted_open_payload",
    "render_deleted_open_text",
    "render_deleted_payload",
    "render_deleted_text",
    "render_df_index_payload",
    "render_df_index_text",
    "render_diff_payload",
    "render_diff_text",
    "render_docker_enrichment_payload",
    "render_docker_enrichment_text",
    "render_explain_path_payload",
    "render_explain_path_text",
    "render_report_payload",
    "render_report_text",
    "render_top_payload",
    "render_top_text",
    "resolve_group_for_path",
    "resolve_snapshot_pairs",
    "resolve_top_level_subtree_group",
    "resolve_top_snapshot_selection",
    "summarize_diff_rows",
]
